load("@rules_java//java:java_binary.bzl", "java_binary")
load("//rule:merge_library.bzl", "kt_merge_library", "merge_library_jar")

kt_merge_library(
    name = "widget_factory_unmerged",
    srcs = glob(["*.kt"]),
    javac_opts = "//combine:javac_opts_jvm_25",
    kotlinc_opts = "//combine:kotlinc_opts_jvm_25",
    resource_strip_prefix = "combine/example/widget_factory/versions/26.3/resources",
    resources = glob(["resources/**"]),
    runtime_deps = [
        "//combine/backend/minecraft/versions/26.3",
        "//combine/theme/blackstone:blackstone_common",
        "//combine/theme/blackstone:blackstone_vanilla",
        "//combine/theme/oreui:oreui_common",
        "//combine/theme/oreui:oreui_vanilla",
    ],
    deps = [
        "//:compose",
        "//combine/backend/minecraft/game/26.3",
        "//combine/core/data",
        "//combine/core/layout",
        "//combine/core/modifier",
        "//combine/core/modifier/drawing",
        "//combine/core/modifier/placement",
        "//combine/core/modifier/scroll",
        "//combine/core/paint",
        "//combine/core/screen",
        "//combine/core/widget/layout",
        "//combine/data",
        "//combine/example/widget_factory/common",
        "//combine/style",
        "//combine/theme/base",
        "//combine/theme/blackstone",
        "//combine/theme/oreui",
        "//combine/theme/vanilla",
        "//combine/widget",
        "//game/26.3:game_client_libraries",
        "@maven//:org_jetbrains_kotlinx_kotlinx_collections_immutable_jvm",
        "@maven_fabric_26_3//:com_terraformersmc_modmenu",
        "@maven_fabric_26_3//:net_fabricmc_fabric_api_fabric_api",
        "@maven_fabric_26_3//:net_fabricmc_fabric_api_fabric_key_mapping_api_v1",
        "@maven_fabric_26_3//:net_fabricmc_fabric_api_fabric_lifecycle_events_v1",
        "@maven_fabric_26_3//:net_fabricmc_fabric_loader",
    ],
)

merge_library_jar(
    name = "widget_factory",
    visibility = ["//visibility:public"],
    deps = [
        ":widget_factory_unmerged",
        "//combine/example/widget_factory/common",
    ],
)

alias(
    name = "26.3",
    actual = ":widget_factory",
    visibility = ["//visibility:public"],
)

java_binary(
    name = "dev_client",
    srcs = [],
    data = [
        "//game/26.3:game_client_assets",
        "//game/26.3:game_client_assets_version",
    ],
    env = {
        "LANG": "en_US.UTF8",
    },
    jvm_flags = [
        "-Dfabric.development=true",
        "-Ddev.launch.version=26.3-snapshot-10",
        "-Ddev.launch.type=client",
        "-Ddev.launch.assetsVersion=$(rlocationpath //game/26.3:game_client_assets_version)",
        "-Ddev.launch.mainClass=net.fabricmc.loader.impl.launch.knot.KnotClient",
        "-Xmx4G",
    ] + select({
        "@platforms//os:macos": ["-XstartOnFirstThread"],
        "//conditions:default": [],
    }),
    main_class = "top.fifthlight.fabazel.devlaunchwrapper.DevLaunchWrapper",
    runtime_deps = [
        ":widget_factory_unmerged",
        "//combine/backend/minecraft/fabric:meta_jar",
        "//combine/backend/minecraft/versions/26.3:meta_jar",
        "//game/26.3:game_client",
        "//game/26.3:game_client_libraries",
        "//rule/dev_launch_wrapper",
        "@maven_fabric_26_3//:io_github_llamalad7_mixinextras_fabric",
        "@maven_fabric_26_3//:net_fabricmc_fabric_language_kotlin",
        "@maven_fabric_26_3//:net_fabricmc_fabric_loader",
        "@maven_fabric_26_3//:net_fabricmc_sponge_mixin",
    ],
)
