# Technetium - NeoForge 26.2
license = "LGPL-3.0-or-later"

[[mods]]
modId = "technetium"
version = "0.0.1"
displayName = "Technetium"
description = "安卓触摸体验优化模组:基于 TouchController,仿基岩版主菜单等。"
authors = "fishqaq123"
logoFile = "assets/technetium/textures/icon.png"

[[mixins]]
config = "technetium.mixins.neoforge.json"

# 依赖 Minecraft 26.2
[[dependencies.technetium]]
modId = "minecraft"
type = "required"
versionRange = "[26.2]"
ordering = "NONE"
side = "CLIENT"

# 依赖 NeoForge
[[dependencies.technetium]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0, 26.2.1)"
ordering = "NONE"
side = "CLIENT"

# 依赖 TouchController 26.2 NeoForge(我们需要 Mixin 它的内部类 + combine 渲染)
[[dependencies.technetium]]
modId = "touchcontroller_26_2_neoforge"
type = "required"
ordering = "NONE"
side = "CLIENT"

# 依赖 combine + combine_26_2(渲染仿基岩菜单)
[[dependencies.technetium]]
modId = "combine"
type = "required"
ordering = "NONE"
side = "CLIENT"

[[dependencies.technetium]]
modId = "combine_26_2"
type = "required"
ordering = "NONE"
side = "CLIENT"

# 依赖 Kotlin for Forge(TC/combine 用 Kotlin)
[[dependencies.technetium]]
modId = "kotlinforforge"
type = "required"
ordering = "NONE"
side = "CLIENT"
